platform :ios, '26.0'

use_frameworks!

target 'PutioSDK_Example' do
  pod 'PutioSDK', :path => '../'

  target 'PutioSDK_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
